nk3nny/LambsDanger

addons/danger/functions/fnc_debugDraw.sqf
addons/danger/settings.sqf

- Don't Create/Use RSC when we don't render them because they are offscreen
- Clear out Rect Caches when Setting is changed instead of every frame when not active
- Add Background to Debug Renderer
- Fixes Position and Scaling of Rect

add 2 small Performance Improvements

---

addons/danger/functions/fnc_debugDraw.sqf

this PR fixes a Scaling issue with Arma UI Sizes (or at least I hop it does)

Improve Text Renderer

---

addons/main/LICENSE
addons/main/script_version.hpp
hemtt.toml

1. Add license file to release builds and into main pbo
2. Set version to 2.0.0

License file and version

---

addons/danger/settings.sqf

Changes the function to add CBA settings to a more secure one.

Use addSetting for security

---

addons/danger/functions/fnc_findCover.sqf
addons/danger/scripts/lambs_danger.fsm

Introduce a new parameter to the `findCover` function.
The new parameter Accepts only a string with possible values:
- ASCEND `default`
- DESCEND 
- RANDOM
If neither `DESCEND` or `ASCEND` is provided then the possible positions are being randomized. `ASCEND` returns closest possible location. `DESCEND` returns farthest possible location.

Introduce Sort Mode parameter for find cover

---

addons/danger/Cfg3DEN.hpp
addons/danger/config.cpp

add 3den checkbox for Radio

---

addons/danger/functions/fnc_assault.sqf
addons/danger/functions/fnc_assaultBuilding.sqf
addons/danger/functions/fnc_checkBody.sqf
addons/danger/functions/fnc_fleeing.sqf
addons/danger/functions/fnc_hideInside.sqf
addons/danger/functions/fnc_immediateAction.sqf
addons/danger/functions/fnc_leaderAssess.sqf
addons/danger/functions/fnc_leaderManoeuvre.sqf
addons/danger/functions/fnc_panic.sqf
addons/danger/functions/fnc_vehicleAssault.sqf
addons/danger/scripts/lambs_dangerCivilian.fsm
addons/eventhandlers/CfgEventHandlers.hpp
addons/eventhandlers/functions/fnc_explosionEH.sqf
addons/main/script_macros.hpp
addons/wp/functions/fnc_taskArtillery.sqf
addons/wp/functions/fnc_taskCQB.sqf
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskGarrison.sqf
addons/wp/functions/fnc_taskHunt.sqf
addons/wp/functions/fnc_taskPatrol.sqf

1. *Small Cleanup in CivDanger FSM*
2. *Cleanup in Config for Lambs_Eventhandlers*
3. *add RND macro and use it*
4. *Cleanup some small spaces in functions*

Small cleanup

---

addons/danger/XEH_PREP.hpp

1. *Emergency PR to fix my Wupsi*

fix my wupsi

---

addons/danger/functions/fnc_shareInformationRange.sqf
addons/danger/settings.sqf
addons/eventhandlers/functions/script_component.hpp
addons/eventhandlers/script_component.hpp

1. *Fixes the #53*
2. *Prevent Users from "Cheating" when activating Debug Settings*

Fix #53 and Disable Debug Settings in For Release

---

addons/danger/functions/fnc_fsmExitVariables.sqf

add Vanilla Revive Compatibility

---

addons/eventhandlers/config.cpp
addons/eventhandlers/functions/fnc_explosionEH.sqf
addons/wp/config.cpp

1. *Cleanup of wrong Indentation*

do small Spacing Cleanup

---

addons/danger/CfgVehicles.hpp
addons/danger/XEH_PREP.hpp
addons/danger/config.cpp
addons/danger/functions/ZeusModules/fnc_moduleDisableAI.sqf
addons/danger/functions/ZeusModules/fnc_moduleDisableGroupAI.sqf
addons/danger/functions/ZeusModules/fnc_moduleSetRadio.sqf
addons/danger/functions/fnc_assault.sqf
addons/danger/functions/fnc_assaultSpeed.sqf
addons/danger/functions/fnc_findCover.sqf
addons/danger/functions/fnc_shareInformation.sqf
addons/danger/functions/fnc_suppress.sqf
addons/danger/scripts/lambs_danger.fsm
addons/main/CfgFactionClasses.hpp
addons/wp/functions/fnc_taskAssault.sqf
addons/wp/functions/fnc_taskRush.sqf
addons/wp/scripts/fnc_wpRush.sqf

ZEUS fixes
- Rename and replaced moduleDangerAI to DisableGroupAI  (better naming scheme)
- Minor updates and fixes to wp/task fixes

ZEUS fixes

---

addons/danger/functions/fnc_findBuildings.sqf

1. Very slightly make it faster
count makes no sense if you need to add a true/false, its slower than forEach that way.
Also in other scripts the semicolon is usually left away on a return.

Optimize fnc_findBuildings

---

addons/danger/functions/fnc_findOverwatch.sqf

1. Make `_fnc_selectResult` more efficient

Optimize fnc_findOverwatch

---

addons/wp/XEH_PREP.hpp
addons/wp/functions/fnc_findClosedTarget.sqf
addons/wp/functions/fnc_findClosestTarget.sqf
addons/wp/functions/fnc_taskCreep.sqf
addons/wp/functions/fnc_taskHunt.sqf
addons/wp/functions/fnc_taskRush.sqf

1. Make fnc_findClosedTarget faster

Optimize fnc_findClosedTarget

---

addons/danger/functions/fnc_fleeing.sqf
addons/danger/functions/fnc_gesture.sqf
addons/danger/functions/fnc_immediateAction.sqf
addons/danger/functions/fnc_leaderManoeuvre.sqf
addons/danger/functions/fnc_panic.sqf
addons/danger/settings.sqf
addons/wp/functions/fnc_taskCQB.sqf

1. *Title*
@nk3nny please check what playMoveNow can be changed to the gesture function and what functions need to be forced.
https://github.com/nk3nny/LambsDanger/pull/74/files#diff-9c21ba0c96b18cb1cdad7fd182e4fcfbR90
https://github.com/nk3nny/LambsDanger/pull/74/files#diff-aa2356a28d779ef1d576b7aabf6f4918R53

add Setting to Disable Gestures

---

addons/danger/XEH_PREP.hpp
addons/danger/functions/debug/fnc_debugDraw.sqf
addons/danger/functions/debug/fnc_debugMarkerColor.sqf
addons/danger/functions/debug/fnc_debugObjectColor.sqf
addons/danger/functions/fnc_assault.sqf
addons/danger/functions/fnc_fleeing.sqf
addons/danger/functions/fnc_gesture.sqf
addons/danger/functions/fnc_immediateAction.sqf
addons/danger/functions/fnc_leaderManoeuvre.sqf
addons/danger/functions/fnc_panic.sqf
addons/danger/functions/fnc_suppress.sqf
addons/danger/functions/fnc_vehicleAssault.sqf
addons/danger/settings.sqf
addons/wp/functions/fnc_taskCQB.sqf

- Added colour to suppression/assault markers
- Added vehicle assault fnc indicator
- Changed to 'simpleObject' rather than local vehicle for markers
- Tweaked debug draw -- uncommented skill information -- added morale information

Debug improvements

---

addons/danger/XEH_preInitClient.sqf
addons/danger/functions/fnc_assaultBuilding.sqf
addons/danger/functions/fnc_assaultSpeed.sqf
addons/danger/functions/fnc_doCallout.sqf
addons/danger/functions/fnc_leaderArtillery.sqf
addons/danger/functions/fnc_leaderCQC.sqf
addons/danger/functions/fnc_panic.sqf
addons/danger/functions/fnc_suppress.sqf
addons/danger/functions/fnc_vehicleSuppress.sqf
addons/main/script_version.hpp
addons/wp/functions/fnc_taskArtillery.sqf
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskGarrison.sqf
hemtt.toml

2.3.1 Hotfixes

---

addons/danger/functions/fnc_doCallout.sqf
addons/danger/functions/fnc_hideInside.sqf
addons/danger/functions/fnc_immediateAction.sqf
addons/danger/functions/fnc_leaderArtillery.sqf
addons/danger/functions/fnc_leaderAssess.sqf
addons/danger/functions/fnc_leaderHide.sqf
addons/danger/functions/fnc_leaderManoeuvre.sqf
addons/danger/functions/fnc_panic.sqf
addons/danger/functions/fnc_react.sqf
addons/danger/functions/fnc_suppress.sqf
addons/eventhandlers/functions/fnc_explosionEH.sqf
addons/main/functions/fnc_getPos.sqf
addons/wp/CfgVehicles.hpp
addons/wp/XEH_PREP.hpp
addons/wp/config.cpp
addons/wp/functions/Modules/fnc_moduleReset.sqf
addons/wp/functions/fnc_taskAssault.sqf
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskCreep.sqf
addons/wp/functions/fnc_taskHunt.sqf
addons/wp/functions/fnc_taskPatrol.sqf
addons/wp/functions/fnc_taskReset.sqf
addons/wp/scripts/fnc_wpRetreat.sqf

- Added taskReset module to ZEUS
- Fixed minor issues with example text in taskPatrol
- Fixed issue with taskCamp where units would occassionally get stuck in animation
- Fixed reduced AI leaders reaction to hostile AIR and tank vehicles*
*NB: WIP will be updated within 30 min

Hotfix 2.3.1 for release today!

---

addons/main/script_version.hpp
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskGarrison.sqf

- remoteExec on taskCamp
- Version number

Hotfix for 2.3.2

---

addons/danger/XEH_postInit.sqf
addons/danger/functions/fnc_eventCallback.sqf

1. *Title*
2. *Remove not needed spawn in eventCallback*

add BIS_fnc_callScriptedEventHandler Wrapper

---

addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/stringtable.xml

Fixed tiny stringtable error in modules creep/hunt/Rush
2. *Each change in a seperate line*

Fixed stringtables

---

addons/danger/functions/fnc_shareInformation.sqf
addons/danger/settings.sqf
addons/danger/stringtable.xml

Add Max Reveal Setting

---

addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/functions/fnc_findClosestTarget.sqf
addons/wp/functions/fnc_taskCreep.sqf
addons/wp/functions/fnc_taskHunt.sqf
addons/wp/functions/fnc_taskRush.sqf
addons/wp/modules.hpp
addons/wp/stringtable.xml

add Player Only Parameter to Creep, Hunt and Rush

---

addons/danger/XEH_PREP.hpp
addons/danger/functions/fnc_nearbyFriendly.sqf
addons/danger/functions/fnc_suppress.sqf
addons/danger/functions/fnc_vehicleSuppress.sqf
addons/danger/settings.sqf
addons/danger/stringtable.xml

1. *Title*
2. *Fixes #93*
3. *Replaces #94 and #95*

Add Suppression Check for Friendly Units

---

addons/main/functions/fnc_showDialog.sqf
addons/wp/Cfg3DEN.hpp
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/functions/fnc_taskGarrison.sqf
addons/wp/modules.hpp
addons/wp/stringtable.xml

Add Sort By Height and Teleport Option to Module Garrison

---

addons/main/script_version.hpp
hemtt.toml

1. *This Will auto Set the Version Number*
2. *Requires HEMTT 0.8.0*

add a way for auto setting Version Number

---

addons/wp/functions/Modules/fnc_moduleCamp.sqf
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/modules.hpp
addons/wp/stringtable.xml

Add teleport option to taskCamp
Tweaks sitting functionality of taskCamp
Fixes default settings in taskGarrison module

Adds teleport option to TaskCamp + minor fixes

---

addons/danger/stringtable.xml
addons/eventhandlers/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

First batch of German translation.

First batch of German translation

---

addons/wp/functions/fnc_taskCreep.sqf
addons/wp/functions/fnc_taskRush.sqf

fix Cycle Time in taskCreep/Rush

---

addons/wp/Cfg3DEN.hpp
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/functions/fnc_taskGarrison.sqf
addons/wp/stringtable.xml
hemtt.toml

add None to ExitTrigger for TaskGarrison

---

addons/danger/functions/fnc_isNight.sqf
addons/danger/functions/fnc_leaderContact.sqf

Makes AI shoot flare on 'CONTACT' state
Increases flare usage.

Adds shooting flare on leaderContact

---

addons/wp/functions/fnc_taskPatrol.sqf

Improve Task Patrols Waypoint Statement Readabilty

---

addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/functions/fnc_findClosestTarget.sqf
addons/wp/functions/fnc_taskCreep.sqf
addons/wp/functions/fnc_taskRush.sqf
addons/wp/modules.hpp

Adds fixes to taskRush
- Corrects function cycle times for taskRush and taskCreep
- Adds dynamic cycle time to taskRush
- Adds small enhancement to taskRush suppression system
- Fixes some distance2D checks

Fixes to taskRush

---

addons/wp/functions/fnc_taskCQB.sqf

Enhance taskCQB
- code cleanup
- Fixed suppression
- Made unit sort buildings by distance to leader rather than wp/module position

Adds Enhanced taskCQB

---

addons/wp/functions/Modules/fnc_moduleReset.sqf
addons/wp/functions/fnc_doArtillery.sqf
hemtt.toml

Fixed moduleReset error 
Fixed debug marker in doArtillery (said check rounds on the main salvo)
Changed version number

Hotfix within a hotfix 2.4.4

---

addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskPatrol.sqf

possible fix for #136

---

addons/main/functions/fnc_doCallout.sqf

Exit doCallout Early when unit is "Mute"

---

addons/wp/functions/Modules/fnc_moduleArtilleryRegister.sqf
addons/wp/functions/Modules/fnc_moduleCQB.sqf
addons/wp/functions/Modules/fnc_moduleCamp.sqf
addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_modulePatrol.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/functions/fnc_findClosestTarget.sqf
addons/wp/functions/fnc_taskCQB.sqf
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskGarrison.sqf
addons/wp/functions/fnc_taskPatrol.sqf

1. *add all Required area data to default when getting it from the Logic*
2. *add Possibility to Limit Area Markers in Height*

Improve Area data for Waypoint Module

---

addons/wp/functions/fnc_taskCamp.sqf

check if weapons are Locked in taskCamp

---

addons/wp/functions/fnc_findClosestTarget.sqf

Fix findClosestTarget selecting friendly side as target

---

addons/main/functions/fnc_doCallout.sqf

Fix a issue doCallout Stopped working

---

addons/wp/Cfg3DEN.hpp
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/modules.hpp

1. *Changes from Custom Build Selection box to Combo Box*
This PR Breaks Backwards Compatibility all settings may be mangled after the PR is merged but it allows us to Add more settings to exitcontions, this is required for #144

Change moduleGarrsion from Custom Selection box to Combo Dropdown

---

addons/danger/stringtable.xml
addons/eventhandlers/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

I saw that you needed help with the translation into Polish, so I decided that I would help.

Polish translation for LAMBS Danger

---

addons/main/XEH_postInit.sqf

Fix Debug Controls where not deleted on Singleplayer restart

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/feature_request.md

Fix tags in issue templates

---

addons/main/XEH_postInit.sqf

Fix issue with debug Variables

---

hemtt.toml
mod.cpp

Write the current version of the release into the mod.cpp file of the built artifact
version++

Add automatic version to mod.cpp

---

addons/main/XEH_postInit.sqf

Add Event Wrapper for Moved Events

---

addons/danger/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

Add missing translation for LAMBS danger,wp and main.

Update for Polish translation (LAMBS 2.5.0 RC)

---

addons/main/XEH_postInit.sqf
addons/main/functions/debug/fnc_debugDraw.sqf
addons/main/settings.sqf

1. *Fix that Controls may not be deleted correctly*
2. *Fix that Debug Controls maybe not shown on Mission Start*
3. *Based on #193*

Fix debug draw caching issues

---

addons/danger/functions/fnc_tacticsContact.sqf

1. Make AI stop shoot friendlies because they are annoyed by them firing at nothing

Remove doFire from tacticsContacts

---

addons/danger/stringtable.xml
addons/eventhandlers/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

1. *Title*
Contributed by FoxnotMulder

Add Russian translation

---

addons/danger/ZEN_CfgContext.hpp
addons/wp/ZEN_CfgContext.hpp

Fix Zen Context Menu Actions Conditions

---

addons/danger/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

Unify NewLines in Stringtables

---

addons/danger/functions/fnc_tacticsHide.sqf
addons/wp/functions/fnc_doAssaultUnitReset.sqf
addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskRush.sqf

1. Fixes launcher selection in fnc_tacticsHide
2. Add some brackets as per code style

fix launcher select in tacticshide and add some brackets

---

addons/danger/settings.sqf
addons/main/settings.sqf

Fix Slider Percentage Issue

---

addons/wp/XEH_preInit.sqf
addons/wp/functions/Modules/fnc_moduleAssault.sqf
addons/wp/functions/Modules/fnc_moduleCQB.sqf
addons/wp/functions/Modules/fnc_moduleCamp.sqf
addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_modulePatrol.sqf
addons/wp/functions/Modules/fnc_moduleReset.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/functions/ZEN/fnc_setCQB.sqf
addons/wp/functions/ZEN/fnc_setCamp.sqf
addons/wp/functions/ZEN/fnc_setCreep.sqf
addons/wp/functions/ZEN/fnc_setGarrison.sqf
addons/wp/functions/ZEN/fnc_setHunt.sqf
addons/wp/functions/ZEN/fnc_setPatrol.sqf
addons/wp/functions/ZEN/fnc_setReset.sqf
addons/wp/functions/ZEN/fnc_setRush.sqf

1. *add Event Wrappers for Task*
2. *use Events for Remote Units in WP*

Convert remoteExec/remoteExecCall to CBA Target Events

---

addons/main/script_macros.hpp

Use CompileScript when DISABLE_COMPILE_CACHE Is used

---

addons/danger/XEH_PREP.hpp
addons/danger/functions/fnc_brain.sqf
addons/danger/functions/fnc_brainEngage.sqf
addons/danger/functions/fnc_brainForced.sqf
addons/danger/functions/fnc_brainReact.sqf
addons/danger/functions/fnc_brainVehicle.sqf
addons/danger/functions/fnc_isForced.sqf
addons/danger/functions/fnc_isForcedExit.sqf
addons/danger/functions/fnc_isLeader.sqf
addons/danger/scripts/lambs_danger.fsm
addons/main/functions/UnitAction/fnc_doDodge.sqf
addons/main/functions/UnitAction/fnc_doHide.sqf
addons/main/script_macros.hpp

Adds exit condition on 'lambs_danger_forceMove' in brainForced
Improved performance of brainEngage by having zero-time exit variables
Improved performance by skipping unnecessary vector additions to suppression

Brain performance and timings

---

addons/main/functions/fnc_isNight.sqf

Improves isNight.sqfo performance in main by use of getEnvSound Controllers.
Improvement suggested by RCA3 on BIS forums. 
https://community.bistudio.com/wiki/getEnvSoundController

Improves isNight check performance by RCA3

---

addons/wp/XEH_preInit.sqf

fix issue with taskAssault calling taskArtillery

---

addons/wp/XEH_preInit.sqf

Prevent Script Errors with TaskArtillery when no Artillery is defined

---

addons/danger/XEH_PREP.hpp
addons/danger/ZEN_CfgContext.hpp
addons/danger/functions/ZEN/fnc_setReinforcement.sqf
addons/danger/functions/ZEN/fnc_showReinforcement.sqf
addons/danger/stringtable.xml

add ZEN Context Actions for Reinforcement

---

addons/danger/CfgVehicles.hpp
addons/danger/XEH_PREP.hpp
addons/danger/functions/ZeusModules/fnc_moduleConfigureGroupAI.sqf
addons/danger/stringtable.xml

1. *Title for consistency between module class name and name*

Rename DisableGroupAI Module to Configure Group AI

---

addons/main/functions/debug/fnc_debugDraw.sqf

Improve Render Positions of DebugDraw

---

addons/danger/scripts/lambs_danger.fsm

As per discussion. Simplified Params array in FSM.  Removed unnecessary default entries

Simplified Params array in fsm

---

addons/formations/$PBOPREFIX$

1. Add pbo prefix file so pbo can be signed properly

add pbo prefix for formations module

---

tools/stringtableChecker/stringTableChecker.js

Improve Regex in stringtableChecker to include Config String macros

---

addons/wp/functions/fnc_doAssaultUnitReset.sqf
addons/wp/functions/fnc_taskAssault.sqf

Fixes units 'walking' when retreat option is enabled in taskAssault
Adds minor performance improvement to animation selection

Fix retreat option in task assault

---

addons/danger/functions/fnc_tacticsAssault.sqf
addons/danger/functions/fnc_tacticsAssess.sqf
addons/danger/functions/fnc_tacticsFlank.sqf

- Require AI to be suppressed
- Remove duplicate smoke usage in tacticsAssess
Answers feedback from a number of sources. Latest being discord.

Fixes excessive use of AI smoke

---

addons/wp/modules.hpp

Cleanup Task Module Configs

---

addons/main/XEH_postInit.sqf
addons/main/functions/debug/fnc_debugDraw.sqf
addons/main/settings.sqf
addons/main/stringtable.xml

1. *Adds more detail to debugDraw Cards*
2. *Cleans up some values that are removed when not set*
3. *Fixes issues that Cards did get drawn at ground level when AI is in building*
4. *the `GROUP LEADER` text is now in the side color*
5. *General Code and Performance improvements*

Improve and optimise debug draw

---

addons/main/functions/UnitAction/fnc_doAssault.sqf
addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
addons/main/settings.sqf
addons/wp/functions/Modules/fnc_moduleArtillery.sqf
addons/wp/functions/Modules/fnc_moduleArtilleryRegister.sqf
addons/wp/functions/Modules/fnc_moduleAssault.sqf
addons/wp/functions/Modules/fnc_moduleCQB.sqf
addons/wp/functions/Modules/fnc_moduleCamp.sqf
addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleGarrison.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_modulePatrol.sqf
addons/wp/functions/Modules/fnc_moduleReset.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/functions/Modules/fnc_moduleTarget.sqf

Remove and Cleanup Todos

---

addons/danger/scripts/lambs_dangerCivilian.fsm

- Fix civilian fsm exit conditions
- Fix bug related to fleeing (which would make unit static!)

Fix civilian fsm exit conditions

---

addons/range/$PBOPREFIX$
addons/range/CfgVehicles.hpp
addons/range/config.cpp
addons/range/script_component.hpp

Add Range Module

---

addons/wp/CfgVehicles.hpp
addons/wp/CfgWaypoints.hpp
addons/wp/ZEN_CfgWaypointTypes.hpp
addons/wp/stringtable.xml

Move WP Strings to Stringtables

---

addons/danger/XEH_preInitClient.sqf
addons/danger/functions/fnc_brainEngage.sqf
addons/danger/functions/fnc_tacticsSuppress.sqf
addons/main/XEH_PREP.hpp
addons/main/XEH_postInit.sqf
addons/main/XEH_preInit.sqf
addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
addons/main/functions/UnitAction/fnc_doSuppress.sqf
addons/main/functions/fnc_shouldSuppressPosition.sqf
tools/sqf_linter_LogChecker.py

1. Adds suppression LOS check function
2. Use LOS check in doSuppression function
3. Enable the check in several tactics

initial suppressive fire check

---

addons/danger/functions/fnc_tacticsContact.sqf
addons/danger/functions/fnc_tacticsHide.sqf
addons/danger/functions/fnc_tacticsHold.sqf
addons/main/XEH_PREP.hpp
addons/main/functions/GroupAction/fnc_doGroupHide.sqf
addons/main/functions/UnitAction/fnc_doHide.sqf
addons/main/functions/debug/fnc_debugDraw.sqf

Adds doGroupHide
- doGroupHide is used in  tacticsContact, taticsHide, tacticsHold
Adds 'forceMove' check to debugDraw
Fixes units reacting with contact state to friendly fire (such as artillery)

Add unified doGroupHide action

---

addons/wp/XEH_preInit.sqf

Use Native Hashes for Artillery System

---

addons/main/XEH_PREP.hpp
addons/main/functions/fnc_findClosestTarget.sqf
addons/wp/XEH_PREP.hpp
addons/wp/functions/fnc_taskCreep.sqf
addons/wp/functions/fnc_taskHunt.sqf
addons/wp/functions/fnc_taskRush.sqf

move findClosestTarget to Main

---

addons/wp/functions/fnc_doArtillery.sqf

Fix Issues that Artillery Guns not Getting Readded in certain cases.

---

addons/danger/settings.sqf
addons/danger/stringtable.xml
addons/wp/settings.sqf

Remove a duplicated stringtable entry

---

tools/stringtableChecker/stringTableChecker.js

add check if StringtableEntries are unused

---

addons/wp/Cfg3DEN.hpp

Fix the 3den Artillery Register Checkbox was not working

---

addons/main/XEH_preInit.sqf
addons/main/settings.sqf
addons/main/stringtable.xml

Move min obstacle proximity to setting

---

addons/wp/settings.sqf

- title
Not sure if the editor attribute is wanted.

Add variable to block auto artillery registration

---

addons/danger/functions/fnc_tacticsAssault.sqf

Fix doUGL script Error

---

addons/main/functions/UnitAction/fnc_doUGL.sqf

1. Fix the issue with `exitWith` within the root scope of the `findIf` command

fix doUgl findIf exitWith issue

---

README.md

Bump up lambs version in the readme badge

---

addons/wp/functions/fnc_taskHunt.sqf
addons/wp/modules.hpp

1. Fixes wrong `params` in task hunt
2. Fix config to use correct string table for "Enabled" and "Disabled"
~~3. used `git add --renormalize .` for those annoying lf crlf things~~
Fixes #288

Fix task hunt module flare issue

---

addons/danger/functions/fnc_brainEngage.sqf
addons/danger/functions/fnc_tacticsAssess.sqf
addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf

Improve use of group level suppression
Tweak suppression chance on "ENEMY_DETECTED" result
Removed "sympathetic suppression"

Optimised Supression feature

---

addons/danger/functions/fnc_brainHide.sqf
addons/main/functions/UnitAction/fnc_doCover.sqf
addons/main/functions/UnitAction/fnc_doDodge.sqf

Streamlines doDodge and removes unecessary doCover related features.
Tweaks doDodge and doCover and BrainHide to reduce glitching-- while also toggling unnecessary features.

Optimised doCover and doDodge

---

CONTRIBUTING.md
addons/danger/stringtable.xml
addons/eventhandlers/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

Add an Italian Translation of LAMBS,
Add Missing German Translations,
Change some German Translations,
Correct some misspelled English phrases.

Added Translation IT/GER

---

addons/wp/functions/fnc_taskReset.sqf

Fixes taskReset resetting animations on unconscious units or those within vehicles

Fix taskReset resetting anims for unconscious or mounted units

---

addons/eventhandlers/functions/fnc_explosionEH.sqf

Fixed explosionEH header
Removed doMove -- made units static

Fixed missing explosionEH Header

---

addons/danger/functions/fnc_tacticsContact.sqf
addons/main/functions/GroupAction/fnc_doGroupHide.sqf
addons/main/functions/UnitAction/fnc_doHide.sqf

Adds suppression option to contact state
Adds use of buildings to contact/assaults
Improved  building sorting algorithm
Prevents units that are not in combat from entering contact/hide cycles

Improved contact state

---

addons/danger/stringtable.xml
addons/eventhandlers/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

I updated the simplified Chinese translation a few days ago. Please merge it

Request to add simplified Chinese Translation

---

addons/danger/functions/fnc_tacticsAssess.sqf

Fix tacticsAssess zero divisor

---

addons/danger/stringtable.xml
addons/eventhandlers/stringtable.xml
addons/main/stringtable.xml
addons/wp/stringtable.xml

Corrected some Chinese mistakes to make it look more natural

Upgrade Chinese translation

---

.github/workflows/main.yml

Fix for Editorconfig-Checker error

---

addons/main/functions/debug/fnc_debugDraw.sqf

- Added 'unitReady' check to card
- Improved display of visibility and danger timeout

Improve fnc_debugDraw

---

addons/main/functions/UnitAction/fnc_doDodge.sqf

Adds prone action to Dodge. (also reduces sliding)

Adds dropping prone to Dodge

---

addons/danger/XEH_preInit.sqf
addons/danger/functions/fnc_brainForced.sqf
addons/danger/scripts/lambs_danger.fsm
addons/formations/CfgFSMs.hpp

Tweaked FSM
Adds interrupt to assaults when units is suddenly crowded by enemies
Fixed excessive reloading in FSM
Fixed vehicles being unable to enter fleeing script Improved better chance of checking dead bodies

Improvements to core FSM

---

addons/main/XEH_PREP.hpp
addons/main/functions/UnitAction/fnc_doSmoke.sqf
addons/main/functions/fnc_getCompatibleThrowMuzzle.sqf

Add Caching to Muzzle Check in doSmokeShell

---

.github/workflows/main.yml
.github/workflows/release.yml
.hemtt/project.toml
tools/nodejs_tools/gitversionsetter.js

1. *Adds a Tool that automatically adds the Git Commit count to the script_version.hpp*

Add Git Commit count as Build Number

---

addons/main/functions/fnc_checkMagazineAiUsageFlags.sqf

1. *Fixes Inconsitent Caching of checkMagazineAiUsageFlags*

Fix Inconsitent Caching of checkMagazineAiUsageFlags

---

addons/wp/functions/fnc_taskCamp.sqf
addons/wp/functions/fnc_taskGarrison.sqf
tools/sqf_linter_LogChecker.py

Allows sub-patrols to re-join main formation on Garrison and Camp tasks
- Good for performance
- Good for combat ability of main group

Improve garrison and task patrols

---

addons/wp/functions/fnc_doAssaultUnitReset.sqf
addons/wp/functions/fnc_taskAssault.sqf

Added support for ground vehicles to taskAssault movement
Improved aggressive infantry behaviour in taskAssault

Added vehicle support to taskAssault

---

addons/main/XEH_preInit.sqf

Fix Macro in Version Mismatch Message

---

addons/danger/functions/fnc_tacticsContact.sqf

What it says. Leaders that are inside keep their soldiers inside the building they area near.

Fix tactics Contact Triggering inside

---

addons/danger/functions/fnc_fsmAllowAnimation.sqf
addons/danger/functions/fnc_tacticsContact.sqf
addons/danger/functions/fnc_tacticsSuppress.sqf
addons/danger/settings.inc.sqf
addons/main/functions/GroupAction/fnc_doGroupStaticPack.sqf
addons/main/functions/GroupAction/fnc_doGroupSuppress.sqf
addons/main/functions/UnitAction/fnc_doDodge.sqf
addons/main/functions/VehicleAction/fnc_doVehicleSuppress.sqf
addons/main/functions/fnc_doShareInformation.sqf
addons/main/functions/fnc_showDialog.sqf
addons/wp/functions/Modules/fnc_moduleCreep.sqf
addons/wp/functions/Modules/fnc_moduleHunt.sqf
addons/wp/functions/Modules/fnc_moduleRush.sqf
addons/wp/functions/fnc_taskArtilleryRegister.sqf

1. *Fixes things that the new Experimental Linter of hemtt found*

fixes from experimental hemtt linter with most aggressive linter settings
