nk3nny/LambsDanger

addons/danger/XEH_PREP.hpp, addons/danger/functions/fnc_findCover.sqf
Adds the function `lambs_danger_fnc_findCover`.
This functions checks close to the unit a spot it potentially seek cover from a given enemy.
The function seeks the closest possible location.
As return value an array is returned which consists of the Position in AGL and as second item the stance. Combined it should be possible to a unit to seek cover.
Right now this function is not implemented into the FSM, yet it is there in case a more dedicated method of finding cover is ever needed.
=> Add function "findCover"

addons/danger/functions/fnc_assault.sqf, addons/danger/functions/fnc_checkBody.sqf, addons/danger/functions/fnc_hideInside.sqf, addons/danger/functions/fnc_leaderAssess.sqf, addons/danger/functions/fnc_shareInformation.sqf, addons/danger/functions/fnc_suppress.sqf, addons/danger/functions/fnc_vehicleJink.sqf, addons/danger/functions/fnc_vehicleRotate.sqf, addons/danger/scripts/lambs_danger.fsm, addons/danger/scripts/lambs_dangerCivilian.fsm
changes - fsm
- Clean up of civilian formation.fsm
- Individual coward fn_hideInside function disabled (ID 69)
- Increased 'timeout' on leader assess delay (+2 seconds)(ID 43)
- Removed redundant investigate 'moveto' pos (ID 34 + ID 36)
- Increased leader time out on Reaciton to contact (+ 3 seconds) (ID 32)
- Added break out of CQC cycle for player led groups (ID 399)
- Fixed Use findNearestEnemy on leader CONTACT event (ID 46)
- Increased timeout on Leader hide form target from 70 to 120 seconds. (ID 48)
- Increased time on Leader Manoeuvre from 30 to 70 seconds (ID 53)
- Increased time on leader Check houses from 10 to 30 seconds (ID 55)
- Increased variability on CQC range (ID 66)
- Tweaked No cowardly behaviour in CQC mode (ID 66)
- Increased chance of immediate Action from 35% to …
=> Tactical_1.4.4_changes 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Issue templates are for creating issues on this repo. People will be able to choose from 4 options.
- Bug report
- Enhancement request
- Feature request
- Regular issue
This should make it easier for when ever people will submit issues. The regular issue option is just a normal issue as you could do it at the moment.
One thing. I am  NOT sure if this PR will enable custom issue templates or not. Maybe they need to enabled by @nk3nny in this repos settings. I am not sure.
=> Issue templates

addons/wp/XEH_preInit.sqf
1. *Fixes that all Units Registered with the function are all assigned the same side*
possible alternative version
the current version is Slower on Multiple entries registered, but because this is only run a select few times there should not be any problem
```sqf
private _tempHash = [[], []];
{
private _index = (_tempHash select 0) find (side _x);
if (_index == -1) then {
_index = (_tempHash select 0) pushBack (side _x);
};
((_tempHash select 1) select _index) pushback _x;
} forEach _this;
{
private _artillery = [GVAR(SideArtilleryHash), _x] call CBA_fnc_hashGet;
private _data = ((_tempHash select 1) select _forEachIndex);
_artillery append _data;
GVAR(SideArtilleryHash) = [GVAR(SideArtilleryHash), _x, _artillery] call CBA_fnc_hashSet;
} forEach (_tempHash select 0);
```
=> Task Artillery Register Multible Side Register Issue

addons/wp/functions/fnc_taskGarrison.sqf
This change fixes accidental assignment of `_b` size of patrol area to `_a`
=> Fixed patrol area size in 'garrizon' waypoint (small typo)

addons/main/functions/fnc_doCallout.sqf
Fixing the Callout Cache behaviour. 
Currently, if we use a Callout Collection we cache the one we choose and only play that one, but we wanted to play differently once every time.
=> Fix a issue with the Cache in doCallout

addons/wp/functions/Modules/fnc_modulePatrol.sqf
On local units, waypoints were always placed at [0,0,0]
from biki
>The "Call" in remoteExecCall does not mean that the execution of the remote executed function / command will happen right away
so the logic would be deleted (line 75) before the `getPos` ran inside taskPatrol function
=> WP - Fix task patrol waypoints being at [0,0,0] for local units

addons/danger/functions/fnc_brainAssess.sqf, addons/danger/functions/fnc_brainEngage.sqf, addons/danger/functions/fnc_brainForced.sqf, addons/danger/functions/fnc_isForced.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/danger/functions/fnc_tacticsHold.sqf, addons/main/functions/UnitAction/fnc_doAssault.sqf, addons/main/functions/UnitAction/fnc_doCover.sqf, addons/main/functions/UnitAction/fnc_doDodge.sqf, addons/main/functions/UnitAction/fnc_doHide.sqf, tools/sqf_linter_LogChecker.py
1. Improvements to the 'running in place'-bug     
2. Fixes movement changes brought on by _queue fix in #174           
3. Adds minor performance improvements to touched functions       
Adds debug variable to tacticsHold
Improves stance change in brainAssess
Improves order of checks in isForced
Improves order of indoor checks in tacticsAssess
Improves performance and tweaks tactical response to long range combat
Improves doAssault performance by removing redundant checks
Fixes running in place issue in doDodge and improves exit conditions
Fixes doCover by forcing speed, increasing cover detection range and streamlining checks
Fixes doHide by forcing speed and re-implementing doStop. (which was necessary to keep AI in buildings)
Fixes redundant "can move" checks in brainAssess
Fixes …
=> Fix running in place with minor performance tweaks

addons/danger/XEH_preInitClient.sqf
Revisits the CBA enabled buttons
ADDS Easy Assault a way to make nearby friendly AI assault buildings and mark buildings inside the _groupMemory_ feature
IMPROVES Easy Suppress by making use of our doSuppress function
IMPROVES Easy Hide by tightening the way buildings are marked
FIXES Easy Suppress by making it multiplayer proof
FIXES toggle AI by resetting _groupMemory_
=> Fixes and improves User Interface

addons/danger/functions/fnc_tacticsReinforce.sqf, addons/danger/stringtable.xml, addons/main/script_macros.hpp, addons/wp/functions/fnc_taskReset.sqf
- Fixes garrisoned and camped units not being able to reinforce
- Fixes reinforcement variable in taskReset
- Updates stringtable to reflect feature
i.e., before this fix. Units set to waypoint Garrison or Camp were not able to reinforce when the 'Reinforcement' variable was enabled.
=> Fixes Garrisoned and Camped reinforcements

addons/danger/functions/fnc_brain.sqf, addons/danger/functions/fnc_brainAssess.sqf, addons/danger/functions/fnc_brainEngage.sqf, addons/danger/functions/fnc_brainHide.sqf, addons/danger/functions/fnc_brainReact.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/danger/functions/fnc_tacticsContact.sqf, addons/main/functions/UnitAction/fnc_doAssaultCQB.sqf, addons/main/functions/UnitAction/fnc_doDodge.sqf, addons/main/functions/UnitAction/fnc_doFleeing.sqf, addons/main/functions/UnitAction/fnc_doHide.sqf
1. Ruthlessly uses exitWith's in the core brain.sqf to save some cycles.
2. Simplifies tacticsAssess.sqf to streamline assessment phase
3. Simplifies and re-orders some function checks for speed.
4. Moves 'SCREAM' event to 'brainHide.sqf' where investigation and hiding actions should go. (improves performance of brainAssess.sqf which is checked more often!)
_Improvements_
Improves brain.sqf performance by using exitWith checks.
Improves brainEngage.sqf performance by tweaking timers and engagement ranges
Improves brainReact.sqf by simplifying timeout
Improves tacticsAssess.sqf by re-ordering checks and using more exitWiths
Improves tacticsContact.sqf timings and removes unneeded stance reset.
Improves doAssaultCQB.sqf exit conditions
Improves doFleeing.sqf exit conditions
Improves …
=> Performance and optimalization

CONTRIBUTING.md, addons/main/XEH_PREP.hpp, addons/main/XEH_preInit.sqf, addons/main/functions/fnc_addShareInformationHandler.sqf, addons/main/functions/fnc_doShareInformation.sqf
1. Add `lambs_main_fnc_addShareInformationHandler` which allows for custom functions to block information sharing (similar to how `ace_explosives_fnc_addDetonateHandler` [works](https://ace3mod.com/wiki/framework/explosives-framework.html#53-detonation-handler)).
2. Add myself to contributor list.
=> Add custom share information handlers

addons/danger/functions/fnc_brainVehicle.sqf, addons/wp/functions/fnc_doArtillery.sqf, addons/wp/functions/fnc_taskArtillery.sqf
Adds artillery crew will disembark when threatened by near enemies
Adds skipCheckRounds will also skip main strike delay*
Adds debug marker for spotter
Fixes check round barrages nearly always be one round
Fixes debug markers were occasionally not removed when caller died
Changes artillery debug markers uses a colour not used by a faction
Changes: static weapon crew will disembark when threatened (instead of only effective commander)
Minor header and variable name clean ups
*This is done according to earlier discussion and the actual description given in stringtables!
=> Improve AI Artillery -- disembarking and improving doArtillery

addons/main/functions/VehicleAction/fnc_doVehicleAssault.sqf
Fixes armored vehicles suppressing  useless positions
Ref bug: https://github.com/nk3nny/LambsDanger/issues/220
Armoured vehicles would occasionally fire random bursts into the air.  The reason for this was that the unit would be put into combat mode, without having knowledge about a targets actual location. If that target was also situated away from buildings. The Armored vehicle would shoot at the "_dangerPos"  which is rarely a useful thing ;) 
Should also prevent reinforcing armoured vehicles from stopping at odd places when reacting to shared information.
=> Fix armored vehicles suppressing useless positions

addons/danger/functions/fnc_brainEngage.sqf
1. Re-implements a slight offset to suppression.  This fixes an error that crops up: units were "yelling" negative because their doSuppress commands failed. 
2. Includes a better handling of speed changes.  This fixes an issue were (particularly) player led groups become very intractable with LAMBS Danger
3. Changes ammunition exit clause to exit at higher round counts.  This will generally prevent AI from assaulting with no ammunition -- and in fact also slows down doSuppression and doAssault  calls.  
Default changed from 30 * 0.15 rounds ~ 4.5 rounds in a 30 round magazine
Will now exit on 30 * 0.2 rounds ~ 6 rounds in a 30 round magazine 
_Changelog_
Fixed units yelling 'Negative' for suppression
Improved handling of speed change when engaging 
Improved exit clause by better balanced …
=> Fix brain engage suppression bug and add minor tweaks

addons/danger/functions/fnc_tacticsContact.sqf
Fixes groups rarely utilising 'aggressive' contact state
Fixes groups often failing to use hand signals and callouts
Changes variable aggressive contact state range to static 120m (can be defined in the future!)
Foolish error on my behalf. I checked for 'free' units, but failed to account for moving ones. 
Static range (120m) is more predictable and can in the future either be configured or thrown into a Define system
=> Fix contact state errors

addons/main/functions/UnitAction/fnc_doAssault.sqf, addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Uncomments stance changes on aggressive (assault) actions.  This reduces the 'enforced' stance changes considerably.  The tweaks works positively by keeping the majority of stance changes on group or defensive actions.  I believe this works with better synergy with our new formations/pathfinding module. 
Fixes units standing up at inopportune times. 
I would like to test this publicly in the SW 2.5.1 'RC'. The features can be easily re-implemented if players experience AI trying to crawl inside buildings in CQB.  In my own testing. That has not tended to occur.
=> Remove assault stance changes

addons/main/functions/fnc_doShareInformation.sqf
Prevents sharing information to player led group. This has the benefit of stopping the group from entering "combat mode" outside the players control. While it does mean that player groups gain less information to engage targets at long range-- the _player_ is present. So that will rarely be an issue!
=> Prevents sharing information to player group

addons/danger/functions/fnc_brainEngage.sqf, addons/danger/functions/fnc_tacticsAssess.sqf
**Refines individual suppression and engagement in three ways:**
1. Makes it possible to quit engagement cycle by setting combatMode to "BLUE" or "GREEN".  I.e., ordering units to hold fire.
2. Halves chance of suppression when enemy is merely 'detected' at not actually considered a target easy to fire at.
3. Removes needReload which wasn't all that successful and also quite slow.
**Refines tacticsAssess:**
* Adds and applies "RANGE_NEAR" define
* Removes Suppression chance when combatMode is "white" -- i.e., group is supposed to hold fire.
* Minor performance improvements by using getPosWorld and getPosATL where relevant
Changes in both functions make the AI less likely to become fully stuck in a suppression loop. Particularly when the enemy isn't actually spotted.
=> Refines Suppression in brainEngage and tacticsAssess

addons/wp/CfgWaypoints.hpp
- Fixes missing taskAssault - Retreat mode waypoint text
- Minor tweaks to other waypoint text.
- Removes reference to 'unit' or 'units' to maintain consistency.
=> Minor fixes to language in waypoints

addons/main/functions/UnitAction/fnc_doSuppress.sqf, addons/main/settings.sqf, addons/main/stringtable.xml
*Values*
1. Changes default value of minimum suppression distance from 28 to 50
2. Clarifies some stringtable text
3. Changes max range of suppression from 280 to 200
*Fixes*
- This means the AI will be less likely to suppress buildings and walls in built up terrain*
- This makes the AI more able to  suppress at range (specifically accounting for weapons like the vanilla AKM which are weirdly configured)*
**logic suppression value**
*For individual AI the change will be minimal. When the AI is within CQB range (by default 60 meters) that option will be preferred instead. For AI that are flanking or suppressing, the effect is more noticeable-- fewer instances of violently suppressing a bush or street sign infront of them.  Combat testing on Livonia demonstrates no problems in forest …
=> Improve Suppression settings and stringtables

addons/danger/functions/fnc_tacticsFlank.sqf, addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
1. Stops AI leaders from supressing while flanking
2. Fixes AI Flanking manoeuvres never closing in to destroy the enemy!
**FIXES LEADERS**
By stopping AI leaders from being picked to deliver suppressive fire. Group cohesion is improved and prevents a few cases where AI group leaders would get stuck when flanking.
**FIXES TACTICS**
By  reducing evaluated distance L72 in fn_tacticsFlank.sqf  we ensure that the AI actually close with and destroy the enemy!  This prevents a few border cases where the AI was seen never to attempt to close in with the enemy and would instead be seen to circle hopelessly around the target.
=> Fixes circular flanking and prevents leaders from suppressing

addons/danger/functions/fnc_tacticsAssess.sqf
1. When group leader was already indoor in a different building
2. When assumed location of AI was away from buildings
=> Fix assault/garrison issue with taskAssess

addons/danger/functions/fnc_brainForced.sqf
LAMBS Danger.fsm adds more instances of the local vehicle "SuppressTarget". On occasion, units will chose them as valid 'ATTACK' targets.  This causes them to stupidly shoot at single locations.
Seems like a vanilla error where SuppressTargets are not always cleaned up.
This, crudely, fixes this by simply deleting suppressTargets which have turned into objects that are instead attacked.
=> Fix units attacking SuppressTargets

addons/main/XEH_PREP.hpp, addons/main/functions/fnc_removeEventhandlers.sqf, addons/wp/XEH_preInit.sqf, addons/wp/functions/Modules/fnc_moduleGarrison.sqf, addons/wp/functions/fnc_taskCamp.sqf, addons/wp/functions/fnc_taskGarrison.sqf, addons/wp/functions/fnc_taskHunt.sqf, addons/wp/functions/fnc_taskReset.sqf, addons/wp/modules.hpp, addons/wp/stringtable.xml
Adds suppression EH to taskGarrison and taskCamp and makes taskHunt closer in style to other functions.
Adds taskCampReset event
Adds 'suppress' as an option to taskGarrison
Adds suppress check to taskCamp
Fixes wrong eventhandlers were selected in garrison module
Improves stance control of units in taskCamp
Improves taskHunt style
Improves cleanups of EHs
Removes suppression feature in taskHunt (better handled through new FSM and group actions)
Changed - order of eventhandlers
=> Improve taskCamp, taskCamp and taskGarrison waypoints with eventhandlers

addons/danger/functions/fnc_brainVehicle.sqf, addons/main/functions/VehicleAction/fnc_doSelectWarhead.sqf
Fix doSelectWarhead error when vehicle role is not a gunner with a turret path
1. Add some more checks before going through each turret
possible fix for #266
=> Fix doSelectWarhead errors

addons/danger/functions/fnc_brainVehicle.sqf, addons/main/functions/VehicleAction/fnc_doVehicleAssault.sqf, addons/main/functions/VehicleAction/fnc_doVehicleRotate.sqf
- Adds check for Air vehicle category
- Fixes duplicate suppression via. vehicleRotate
- Fixes vehicles spamming shareInformation
- Changes suppression timing randomisation somewhat to allow for slightly greater suppression intervals
**Logic**: 
1. Stops doVehicleRotate from calling suppression. That is better done via. doVehicleAssault which will happen 2 seconds later. This prevents suppression spam and also makes doVehicleRotate a more useful _generic_ function.
2. Changing doShareInformation to only happen on _first_ enemy contact greatly reduces spam (especially bad considering the long range of vehicle communication.
3. Air vehicles are prevented from communicating enemy locations by design. Air vehicles tend to confuse themselves (and crash or get stunned) enough as is.
4. …
=> Improve vehicle brain by adding Air category and improving suppression

addons/wp/functions/ZEN/fnc_setPatrol.sqf
=> Fix Zen Action for TaskPatrol calling wrong Event

addons/danger/XEH_preInit.sqf, addons/danger/functions/fnc_brain.sqf, addons/danger/functions/fnc_tacticsContact.sqf, addons/danger/functions/fnc_tacticsGarrison.sqf, addons/danger/functions/fnc_tacticsHide.sqf, addons/danger/functions/fnc_tacticsHold.sqf, addons/danger/functions/fnc_tacticsReinforce.sqf
Fixes units becoming stuck in combat mode
Fixes units being triggered to enter combat/contact mode due to friendly fire
**Implementation**
1. Changes the share information feature to trigger a more directly hiding.
2. Prevents all tactics level actions from setting behaviour
3. Small fix brain.sqf to "FIRE" and other immediate actions to sort friendly units*
*For a small sake of performance I'm not sorting for all friendly sides-- Instead I am focused only on units which are the same _side_ as the shooter.  Especially as it seems like allied sides trigger combat behaviour regardless.
**Changes**
This change will mean that units will be somewhat less immediately responsive to enemy fire -- but on the positive side, they'll actually reset when the threat is dealt with(!). 
I also suspect …
=> Fix combat mode errors

addons/danger/functions/fnc_tacticsAssault.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/danger/functions/fnc_tacticsFlank.sqf, addons/danger/settings.sqf
1. Re-add the smoke grenade usage config option
2. Prevent AI from using smoke grenades if the CBA option is checked
I put the check before doSmoke is called, unsure if it would be better to just do one check after doSmoke is called versus preventing doSmoke from being called if the check doesn't pass, easy to change regardless so let me know which one would be better
=> implement smoke grenade usage as a config option

addons/danger/functions/fnc_brainForced.sqf
Occasionally units will get "locked in" to attacking allied suppressTargets -- this results in the unit failing to move.
Deleting the target _and_ doWatch objNull fixes it.
=> Fix: Prevents units from failing to forget their previous attack target

addons/wp/functions/fnc_taskCamp.sqf
Prevents taskCamp sentry wp from resetting animations on units that are mounted. Especially loaded in turrets!  OLD BUG!
=> Fix taskCamp forcing animations on units in vehicles

addons/danger/functions/fnc_tacticsContact.sqf, addons/main/functions/GroupAction/fnc_doGroupHide.sqf
This pull request is focused on tacticsContact and doGroupHide timings and distances.  Increased time and distance for building checks makes the state more dependable and more noticeable.
- Increases the time units may be locked in a AI forced state.
- Changed to use CQB range for close check in contact
=> Improve doGroupHide and tacticsContact timings

addons/danger/functions/fnc_brain.sqf
Fixes units getting stuck in endless dodging patterns.  The change is simple: units that are "highly suppressed" simply stop dodging.  They are already quite combat ineffective, and usually busy getting shot to pieces anyhow!
=> Improve AI dodging evaluation

addons/danger/functions/fnc_brainAssess.sqf, addons/danger/functions/fnc_brainEngage.sqf, addons/main/functions/UnitAction/fnc_doAssault.sqf, addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
This pull request tunes AI close quarter battle ability and introduces small bug fixes.  It does this by tuning behaviours and introducing a change in how groupMemory entries are handled by groups. _See below_.
**brainEngage.sqf**
- Tweaks various brainEngage timings for increased aggression
- Increased chance of suppressing enemyDetected (taking advantage of improved suppress AI added in previous releases)
- Fix Units will only set "ACE_medical_ai_lastFired" when in CQB
- Fix Units will no longer suppress quickly moving vehicles, such as aircraft
**brainAssess.sqf**
- Removes many features from brainAssess which were necessary with the earllier slower brainEngage timings.
- Slimmer and better performing.
**doAssault.sqf**
- Better handling of stance in doAssault. (More standing means …
=> Improve assault memory and engagement routines

addons/danger/functions/fnc_tacticsGarrison.sqf, tools/sqf_linter_LogChecker.py
Adds better groupMemory handling
Adds use of doWatch to focus group
Tweaks Increased distance check (from 25 to 42 meters) 
Changes buildings now sorted by distance (instead of height)
Removes cover being added to movement locations
More information - see below. 
----
Changes sorting of building locations from by height to distance to leader, which makes movement much more reliable.  It also gets to practically the same situation -- as the group leader generally is on the ground.
Removes Adding nearby cover to building positions. Better handling of building positions is more than enough.
This change affords a tweak to building search range, i.e., increased.  It also allows for  better handling of groupMemory. (Unused positions are added to memory).
=> Improve Garrison group tactics

addons/danger/functions/fnc_tacticsAssault.sqf, addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
This pull request adds a significantly improved assault pattern.  At its core the biggest change are tuned timings and distances, and introducing sorting of building/enemy locations by distance to leader.  This means that the squad will converge on each location in an organised fashion-- where previously they did so more randomly in a shotgun pattern.
_doGroupAssault.sqf_ has been improved with breakout patterns (when an AI is immediately threatened by AI) and a better tuned movement speed-- meaning the units will move with their weapons raised, rather than sprinting. Obviously more conducive to assaulting...
=> Improve Assault group tactics

addons/danger/functions/fnc_tacticsAssess.sqf
- Adds sorting enemies based on distance
- Fixes groups failing to deploy static weapons (and sometimes UGL flares)
- Changed - reverts Suppression chance to accomodate #304
- Removed vanilla attack feature from groups*
*This is a big one which we've talked about internally before. What this does is remove the lock-in units sometimes suffer due to the vanilla ATTACK pattern/fsm.  I propose to check this on the development version.
Our own _group_ level attack patterns are better than the individual vanilla ones. But the AI is a complicated beast. Additional testing should be done.
=> Improved tactics assess

addons/danger/functions/fnc_tacticsAssault.sqf, addons/danger/functions/fnc_tacticsFlank.sqf, addons/danger/functions/fnc_tacticsGarrison.sqf, addons/danger/functions/fnc_tacticsHide.sqf, addons/danger/functions/fnc_tacticsSuppress.sqf
Improve description of markers used in debug mode for group level actions
=> Improve tactics debug markers

addons/main/functions/GroupAction/fnc_doGroupStaticFind.sqf
Unit leaders were removed group _units array but never reinserted. Meaning group actions were always undertaken without group leader!
=> Fix failed to reinsert leader when finding static weapons

addons/danger/functions/fnc_tacticsAssault.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/danger/functions/fnc_tacticsFlank.sqf, addons/danger/functions/fnc_tacticsGarrison.sqf, addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
Added Anti-Armour routines to tacticsAssess
- necessitated by changes to enableAttack
Added waypoint check. Units set to "HOLD" will prefer remaining static
Fixed units using binoculars indoors
Timing changes to tacticsAsssault
Improved tacticsAssault
- Better use of groupMemory
- Sorted building positions by closeness
=> Improvements to tacticsAssess states

addons/main/functions/debug/fnc_debugDraw.sqf
=> Prevent Sensor Data to be Requested on Remote Units when Debug Draw is enabled

addons/main/XEH_preInit.sqf
=> Add Error when Loading Lambs only on Clients but not on the Server

addons/danger/functions/fnc_brainAssess.sqf, addons/danger/functions/fnc_brainEngage.sqf, addons/danger/functions/fnc_brainForced.sqf, addons/danger/functions/fnc_isForced.sqf, addons/danger/functions/fnc_isForcedExit.sqf, addons/danger/functions/fnc_tacticsAssault.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/danger/functions/fnc_tacticsAttack.sqf, addons/danger/functions/fnc_tacticsContact.sqf, addons/danger/functions/fnc_tacticsFlank.sqf, addons/danger/functions/fnc_tacticsGarrison.sqf, addons/danger/functions/fnc_tacticsHide.sqf, addons/danger/functions/fnc_tacticsHold.sqf, addons/danger/functions/fnc_tacticsSuppress.sqf, addons/danger/scripts/lambs_danger.fsm, addons/main/functions/GroupAction/fnc_doGroupAssault.sqf, addons/main/functions/UnitAction/fnc_doAssault.sqf, addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf, addons/main/functions/UnitAction/fnc_doFleeing.sqf
Added reload check before group assaults
Added debug markers to various Contact states
Added visibility checks to many clearing routines
Added prioritisation of enemies on the same floor to many clearing routines
Improved doAssault and doAssaultMemory
Improved cqb reaction speed by removing doWatch from many functions Improved tacticsAssault building selection criteria Improved FSM exit condition when the group has memory
Fixed unecessary FSM reset when AI is forced
Fixed tacticsGarrison rarely functioning
=> Improve assault behaviour

addons/main/functions/fnc_doCallout.sqf
Fix extra space in doCallout 'FlankLeft'
Yeah. That is annoying.
=> Fix extra space in doCallout

addons/danger/functions/fnc_tacticsFlank.sqf, addons/main/functions/GroupAction/fnc_doGroupFlank.sqf
Improved survivability by making AI first drop prone, then delaying movement
Fixed header issue
Fixed wrong variable being checked when throwing smoke grenades
Fixed crew dismounting vehicles to conduct flanks. VERY silly with APCs...
=> Improve tacticsFlank feature

addons/main/functions/debug/fnc_debugDraw.sqf
- Added flag for the 'isHidden' command. Which functionality remains rather opaque.
- Improved debug Draw by adding distance in meters to destination -- makes balancing other things easier.
=> Add distance in Meters to debugDraw

addons/main/functions/GroupAction/fnc_doGroupHide.sqf
Adds forced stance change on doGroupHide. 
The benefit is greater survivability for infantry reacting to contact, or adopting a hiding stance due to assessing enemy threats.
1. Needs more internal testing first.
2. Somewhat breaks with philosophy of avoiding to affect permanent stances
=> Add forced stance change on doGroupHide

addons/danger/functions/fnc_tacticsAssess.sqf
Improved group tactics assessment
Reduces chance that smaller groups of 2-3 soldiers enter a proper group-tactic mode. Instead these can rely on the standard FSM to add survivability.
=> Tweak chance to enter group tactics mode

addons/danger/functions/fnc_tacticsContact.sqf, addons/main/functions/GroupAction/fnc_doGroupSuppress.sqf, addons/main/functions/fnc_isIndoor.sqf, tools/sqf_linter_LogChecker.py
Added a follow-up fire state to suppression states
Improves interaction with _doAssaultMemory_ (more predictable) Fixes vehicles being part of Contact state
=> Improve Group and Contact Suppression

addons/danger/functions/fnc_brainVehicle.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/danger/functions/fnc_tacticsFlank.sqf, addons/main/functions/GroupAction/fnc_doGroupFlank.sqf, addons/main/functions/GroupAction/fnc_doGroupStaticFind.sqf, addons/main/functions/UnitAction/fnc_doFleeing.sqf, addons/main/functions/VehicleAction/fnc_doVehicleAssault.sqf, addons/main/functions/VehicleAction/fnc_doVehicleRotate.sqf
Improved the way DangerPos is handled in the vehicle brain, stopping even more cases of knowledge the AI shouldn't have-- and fixing an issue where the AI would sometimes suppress the sky!
Added troops manning static weapons will now abandon them if they run out of ammo
Added - soft-skinned, wheeled vehicles will try to JINK if explosions hit nearby.
Improved dismount/rotate logic of IFVs and APCs
Improved taskFlank use of vehicles. (on the last cycle, vehicles will move to move position)
Improved doFleeing handling of vehicles
Improved doVehicleRotate performance in minor ways
Fixed issue where AI would have more knowledge than appropriate
Fixed rare issue where assessing or flanking units would abandon vehicles
Fixed - Groups will now ignore empty static weapons.
Fixed Rare issue where …
=> Improvements to vehicle Brain

addons/danger/functions/fnc_brainAssess.sqf, addons/danger/functions/fnc_brainEngage.sqf, addons/danger/functions/fnc_tacticsAssault.sqf, addons/danger/functions/fnc_tacticsAssess.sqf, addons/main/functions/GroupAction/fnc_doGroupAssault.sqf, addons/main/functions/UnitAction/fnc_doAssault.sqf, addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf, addons/main/functions/UnitAction/fnc_doDodge.sqf
Added 'half step' movement to doGroupAssault and doAssaultMemory to force movement
Improved tacticsAssault timings, and prevents useless positions to be added
Improved tactical assessment when assaulting
Improved units about to fire rockets are prevented from dodging
Fixed Units set to hold fire, stopped, or ordered to remain stealthy will no longer clear buildings
Fixed potential 'shooting into air' occurrences
Fixed situations where AI would ignore enemies behind them!
Misc performance improvements
Individual actions: In addition to some performance improvements, the biggest addition is the introduction of a half-step state  when assaulting positions in the group memory. This prevents the issue where the AI would sometimes have trouble pathing inside buildings, particularly second …
=> Improved Handling of assaulting Group Memory positions

addons/main/functions/fnc_findBuildings.sqf
Find doors faster by searching for the doors in ``viewGeometry`` ~~and using ``select`` to run the string filtering in-engine.~~
We can assume that doors are found in ``viewGeometry`` because this LOD is used for vision occlusion, which of course includes doors.
This new method is approximately ~4 times faster.
This also coincidentally fixes an issue where the same door positions get detected multiple times due to multiple selections having the same position, things like ``door_1`` and ``door_1_handle``.
``toLower`` is not necessary because all selections must be named lowercase.
Tested on random buildings on: Stratis, Livonia, Takistan, Chernarus, Lythium
**Further testing is encouraged!**
- Remove …
=> Optimize door finding in findBuildings

addons/eventhandlers/functions/fnc_explosionEH.sqf
Adds an alive check to the start, to make sure that code never gets run on dead units (hopefully fixes #328 )
Utilizes a new engine feature for getting the position of the explosion, allowing units to "flinch" accordingly
- Add alive and null checks to the start
- Utilize ``_source`` for getting a position to "flinch" from
=> Improve explosionEH

addons/main/functions/fnc_findBuildings.sqf
- Add two new conditions to the building filter: alive check and hidden check
- Alive check because when buildings get destroyed in Arma, the old building disappears and a ruin is spawned on top, so technically there are now two buildings. The invisible "dead" building and the newly spawned ruin version of the building. The ruin cannot "die" so this will simply filter out the "ghost" building.
- Hidden check because in rare circumstances mission makers might hide buildings, and we don't want to care about those.
- Add alive check to remove unnecessary "ghost" buildings from the array
- Add hidden check to remove invisible buildings from the array
=> Improve building filtering

addons/main/functions/fnc_findReadyVehicles.sqf
- Add a magazine check to ``fnc_findReadyVehicles`` to see if the vehicle has any ammo left
- This is because ``canFire`` does not check for ammo
- Add a magazine check to ``fnc_findReadyVehicles`` to see if the vehicle has any ammo left
=> fnc_findReadyVehicles ammo check

addons/main/functions/fnc_showDialog.sqf
This PR is a small fix to the type declaration of `params`.
When an array is passed to `params`, its third value is an array of objects representing their types (see example 5 in https://community.bistudio.com/wiki/params). This array was empty, which would represent that ~~no~~all types are allowed (see comment). Given that the default is an empty array, I suspect that what we mean is that parameter `_values` of `_fnc_AddDropDown` expects an object of type array. This PR does this.
Found while analyzing the code with https://marketplace.visualstudio.com/items?itemName=SQF-analyzer.sqf-analyzer
=> Fixed type declaration

addons/danger/scripts/lambs_danger.fsm
Optimize queue checking by changing the evaluation order to reduce function calls
- Check queue size before calling ``lambs_danger_fnc_isForced``
=> Change evaluation order in queue check

addons/danger/XEH_preInit.sqf, addons/main/functions/UnitAction/fnc_doFleeing.sqf, addons/main/functions/UnitAction/fnc_doHide.sqf, addons/main/functions/fnc_doShareInformation.sqf, addons/main/functions/fnc_getShareInformationParams.sqf
This patches some of the issues pertaining to constant dismounting of units. 
It does this by rethinking how information is shared, and fixing a bug in doFleeing (which would not take into account the units current situation very well). Information is now only passed for units that are within "combatShareRange"  ~ 200 meters by default.  Units outside this distance, but within radio range, will unless busy, instead turn towards the direction of the unit calling for aid. 
Hiding is also tweaked to make that contact response more effective, which again translates into fewer repetitive executions of said command.
=> Fix issues relating to constant dismounts

addons/formations/CfgVehicles.hpp
Tweaks config to make LAMBS Danger be less interrupted by vanilla stance changes
=> Fix Let LAMBS Danger control unit stances

addons/wp/functions/fnc_doArtillery.sqf, addons/wp/functions/fnc_taskArtilleryRegister.sqf, addons/wp/stringtable.xml
**Improves Dynamic Artillery support for MLRS style launchers.** 
- MLRS launchers will now shoot their entire magazine. Launchers with large magazines will still clump their salvos in 2's or 4's to ensure good spread on target. 
- MLRS launchers will have no check rounds-- which make them quite dangerous in numbers.
=> Adds better support for MLRS artillery

addons/danger/functions/fnc_tacticsAssault.sqf, addons/danger/functions/fnc_tacticsContact.sqf, addons/danger/functions/fnc_tacticsFlank.sqf, addons/danger/functions/fnc_tacticsSuppress.sqf
Fixes Suppress, Flank and Assault group level actions -- where sometimes Units would shoot into air
Fixes units shooting UGL sometimes not partaking in assault.
=> Fixes some instances of groups shooting into air

addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
Improves how AI groups clear buildings by dividing teams into impromptu "Fireteams". Especially effective for larger groups.
=> Improves fnc_doGroupAssault

addons/danger/functions/fnc_brainAssess.sqf, addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Fixes doAssaultMemory.  Bad sorting caused units to continiously forget group positions (and hence not clear them)
Improves doAssaultMemory by adding an exit condition, and requiring the AI not to be suppressed when attempting to clear through buildings in a more organized fashion.
=> Fixes and improves doAssaultMemory

addons/danger/functions/fnc_brainVehicle.sqf, addons/danger/functions/fnc_tacticsAssault.sqf, addons/main/functions/GroupAction/fnc_doGroupFlank.sqf, addons/main/functions/VehicleAction/fnc_doVehicleJink.sqf, tools/sqf_linter_LogChecker.py
Adds Vehicle smoke usage when dropping off troops, or Jinking/dodging danger
Adds road checks to Assault, Flank and VehicleJink (to improve manoeuvrability)
Adds pseudo-fire team based bounds to infantry flanking together with Vehicles. 
Relies on #341
=> Improve vehicle maneuverability and defenses

addons/danger/functions/fnc_tacticsReinforce.sqf
Adds new features to tacticsReinforce
Adds groups set to reinforce will appropriate vehicles (of their side) to use for transport
Adds groups will take ownership of static weapons (and pack them for their use)
Adds groups will check dead bodies for useful weapon before rienforcing
Improves more reliable packing and deploying of static weapons
Improves more formations used
Fixes "HOLD", "GUARD", and "DISMISS" waypoints not being cancelled
Overall this is a considerable enhancement to how units with the reinforcement flag function.  They will much more reliably collect nearby resources before moving to reinforce, and add considerable dynamic potential to operations
=> Add features to fnc_tacticsReinforce.sqf

addons/main/functions/fnc_doCallout.sqf
1. *Possible Replacement for #380*
It is generally slower than #380, but it does not matter because it gets cached for the benefit of fewer false discards.
=> Use file exists for do callout

addons/wp/CfgWaypoints.hpp, addons/wp/stringtable.xml
=> Add Deprecated to Vanilla Waypoints

addons/range/CfgVehicles.hpp
Replaces the *Man* class in the range addon with the classes modified by the danger addon for consistency. And also because *Man* applies to all animals too, which is probably not necessary.
Replace *Man* class with the classes modified by the danger addon (*SoldierWB*, *SoldierEB*, *SoldierGB*)
Alternatively we can also modify *CAManBase*, but I think consistency with the application of fsmDanger is the best option.
=> Remove Man class usage from range addon

addons/main/XEH_preInit.sqf
=> Extend Error Message for when the Mod is not loaded on the Server

addons/danger/functions/fnc_brainForced.sqf
=> Fix BrainForced used PRONE instead of DOWN

addons/wp/XEH_preInit.sqf, addons/wp/functions/fnc_taskCamp.sqf, addons/wp/functions/fnc_taskGarrison.sqf
Adds garrisoned units that are placed outside will appear to look out from building
Improves garrison behaviour when there are no **indoor** locations (fixes issue #413)
Fixes units being teleported to building positions located in air
Fixes taskCamp units sometimes throwing double animation resets
Fixes taskCamp units failing to reset animations
--
Prefers using **setVehiclePosition** rather than **setPos** when placing units.  While more expensive, _taskGarrison_ and _taskCamp_ are not run frequently.  This neatly fixes many issues where units were spawned in the air (and fell to their deaths!) 
With the new and **improved eventhandlers** makes resetting animations in _taskCampReset_ is much more reliable. Therefore no need to run the function multiple times on all units.
=> Improvements to taskGarrison and taskCamp

addons/main/XEH_postInit.sqf, addons/main/functions/VehicleAction/fnc_doSelectWarhead.sqf, addons/main/functions/fnc_doAnimation.sqf, addons/main/functions/fnc_doCallout.sqf, addons/main/functions/fnc_getShareInformationParams.sqf, addons/main/functions/fnc_showDialog.sqf
=> change toLower to toLowerANSI

addons/main/functions/UnitAction/fnc_doSmoke.sqf
Use modern commands to make ``lambs_main_fnc_doSmoke`` slightly faster.
- Use modern commands to make ``lambs_main_fnc_doSmoke`` slightly faster.
Performance increase comes from not having to find throwables from magazines and the potential of not having to call ``getCompatibleThrowMuzzle``. We still need to use it if we don't get a muzzle, because ``throwables`` does not return muzzles for all the throwables it finds (see: [biki example 1](https://community.bistudio.com/wiki/throwables)).
Requires Arma 3 version 2.18. Tested to work in singleplayer on the current 2.18 RC release.
=> Utilize throwables command

addons/eventhandlers/CfgEventHandlers.hpp, addons/eventhandlers/XEH_PREP.hpp, addons/eventhandlers/functions/fnc_delayExplosionEH.sqf
1. Add a delay to explosionEH dependent on:
- Distance from AI
- Auditory response times
- AI Skill
=> Eventhandlers - Add Delay to AI Explosion Reaction

addons/danger/functions/fnc_tacticsAssault.sqf, addons/main/functions/GroupAction/fnc_doGroupAssault.sqf
Fix tacticsAssaults were bugged potentially leaving units with FSM switched off
Improve Take advantage of "getUnitState"
Improve sort building positions to ensure nearest spots are always used 
Improve use groupMemory as function goes along -- to prevent rechecking cleared positions
=> Fix group assaults

addons/danger/functions/fnc_brainEngage.sqf, addons/main/functions/UnitAction/fnc_doAssault.sqf, addons/main/functions/UnitAction/fnc_doAssaultMemory.sqf
Improve **brainEngage** by taking advantage of _getUnitState_
Improve **brainEngage** reimplements behaviour not triggering when **stealthed***
Fixes _doAssault_ where a unit would sometimes get stuck trying to check a position that the group believed the enemy is-- where it clearly could not be. (such as in the sky)**
*Not triggering _brainEngage_ when a unit is sneaking means that the AI become more predictable for player led groups, and unit set to ambush actually remain-ambushing.  Those set to sneak will not get mixed commands from their dangerAI
**It does this by simply forgetting the enemy, which is somewhat controversial but works very well in the context of group memory (i.e., if it is near a building, it will still have likely places to check). 
Makes me think we really should …
=> Improvements to brainEngage

addons/danger/functions/fnc_brainReact.sqf, addons/main/functions/UnitAction/fnc_doCover.sqf, addons/main/functions/UnitAction/fnc_doDodge.sqf
Take advantage of new _getUnitState_ command
Fix some cases of units warping through cover
Improve Dodge and Cover conditions. Units are more likely to drop prone and appear suppressed if under heavy fire.
=> Improve Dodging and reactions

addons/eventhandlers/functions/fnc_explosionEH.sqf, addons/main/XEH_postInit.sqf, addons/main/functions/fnc_doAnimation.sqf, addons/wp/functions/fnc_doAssaultUnitReset.sqf, addons/wp/functions/fnc_taskAssault.sqf
Adds removeExec to animations on explosions to ensure they actually trigger.
=> Improve ExplosionEH animations with CBA Events
